from collections.abc import Sequence
from contextlib import AbstractContextManager
from typing import Protocol

from .operator_types import FixtureCodec, NamedModel, Value


class ModelBackend(Protocol):
    model: NamedModel
    codec: FixtureCodec
    forward_calls: int
    def inference(self) -> AbstractContextManager: ...
    def clock(self) -> float: ...
    def synchronize(self) -> None: ...
    def reset(self) -> None: ...
    def begin(self, rows: Sequence[Sequence[int]]) -> None: ...
    def forward(self, rows: Sequence[Sequence[int]]) -> Value: ...
    def greedy(self, logits: Value) -> tuple[int, ...]: ...
    def cpu_logits(self, logits: Value) -> tuple[tuple[float, ...], ...]: ...
    def cache_length(self) -> int: ...
    def weights_stamp(self) -> tuple[int | float, ...]: ...
    def close(self) -> None: ...
