"""CPU tests of the real runner surface, without importing a GPU stack."""

import importlib
from pathlib import Path

import json
import subprocess
import sys
import pytest

from tests.c3_tiny_backend import TinyBackend

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "results/c3-qwen3-4b-operator-goals"


def test_prepare_when_frozen_contract_is_supplied() -> None:
    # Given: the approved, locally available T1 artifacts.
    path = ROOT / "examples/c3_qwen3/model_runner.py"
    assert path.is_file(), "T4 resident runner implementation is absent"
    api = importlib.import_module("examples.c3_qwen3.model_runner")
    # When: preparation is CPU-only and does not construct a model.
    prepared = api.prepare(RAW / "contract.json", RAW / "preflight.json")
    # Then: exact frozen workload, not a replacement tiny corpus.
    assert len(prepared.prompts_by_id) == 58
    assert sum(len(p.input_ids) for p in prepared.prompts_by_id.values()) == 84096
    assert prepared.asset_spec.revision == "1cfa9a7208912126459214e8b04321603b3df60c"


def runner(tmp_path: Path):
    api = importlib.import_module("examples.c3_qwen3.model_runner")
    assert hasattr(api, "ResidentRunner"), "resident lifecycle is absent"
    prepared = api.prepare(RAW / "contract.json", RAW / "preflight.json")
    backend = TinyBackend()
    return api.ResidentRunner(prepared, backend, tmp_path), backend, prepared


@pytest.mark.parametrize("case", [("ttft", 4, 4), ("single", 2, 256), ("multi", 8, 1024)])
def test_goal_windows_when_complete_generation_runs(tmp_path: Path, case: tuple[str, int, int]) -> None:
    # Given: the actual frozen shapes with a numerical stateful backend.
    goal_id, count, tokens = case
    resident, backend, prepared = runner(tmp_path)
    goal = next(g for g in prepared.contract.goals if g.id == goal_id)
    # When: warmup and real complete requests/wave run through one resident model.
    report = resident.measure(goal, goal.search_prompt_ids)
    raw = json.loads(report.raw_path.read_text(encoding="utf-8"))
    # Then: exact counts and native timestamp windows, not a latency proxy.
    assert report.evaluation.valid, report.evaluation.detail
    assert report.evaluation.metrics["completed_requests"] == count
    assert report.evaluation.metrics["output_tokens"] == tokens
    waves = raw["data"]["waves"]
    assert sum(w["warmup"] for w in waves) == 1
    scored = [w for w in waves if not w["warmup"]]
    for wave in scored:
        assert len(wave["token_ready_s"]) == goal.output_tokens
        assert wave["cache_lengths"] == list(range(goal.input_tokens, goal.input_tokens + goal.output_tokens))
    if goal_id == "single":
        wave = scored[0]
        assert report.evaluation.score == pytest.approx(127 / (wave["token_ready_s"][-1] - wave["token_ready_s"][0]))
    if goal_id == "multi":
        assert backend.batch_history == [8, 8]
        wave = scored[0]
        assert report.evaluation.score == pytest.approx(1024 / (wave["finished_s"] - wave["accepted_s"]))
    if goal_id == "ttft":
        assert report.evaluation.score == pytest.approx(11.0)


def test_resident_reset_when_two_trials_share_weights(tmp_path: Path) -> None:
    # Given: the same backend and immutable weight instance across evaluations.
    resident, backend, prepared = runner(tmp_path)
    goal = next(g for g in prepared.contract.goals if g.id == "single")
    first = resident.measure(goal, goal.search_prompt_ids)
    # When: a second complete evaluation resets request state without loading weights.
    second = resident.measure(goal, goal.search_prompt_ids)
    # Then: token sequences repeat and cache positions restart from the prompt each request.
    a = json.loads(first.raw_path.read_text())["data"]["waves"]
    b = json.loads(second.raw_path.read_text())["data"]["waves"]
    assert [w["tokens"] for w in a if not w["warmup"]] == [w["tokens"] for w in b if not w["warmup"]]
    assert backend.loads == 1
    assert sum(p == (256,) for p in backend.position_history) == 5
    resident.close()
    assert backend.closed


def test_missing_oracle_when_quality_is_requested(tmp_path: Path) -> None:
    # Given: no original-baseline continuation has been supplied.
    resident, _, _ = runner(tmp_path)
    # When: quality is requested on the calibration prompts.
    report = resident.quality(("calibration-calibration-00", "calibration-calibration-01"), tmp_path / "absent.json")
    # Then: missing quality is an explicit failure, never a passing default.
    assert not report.valid
    assert report.detail


def test_teacher_forced_quality_when_candidate_changes_numerics(tmp_path: Path) -> None:
    # Given: original-baseline continuation/logits, generated by the actual numerical model.
    resident, backend, _ = runner(tmp_path)
    assert hasattr(resident, "create_oracles"), "sequential original-baseline oracle generation is absent"
    ids = ("calibration-calibration-00", "calibration-calibration-01")
    oracle = resident.create_oracles(ids)
    assert resident.quality(ids, oracle).valid
    original = backend.model.scale.forward
    # When: a wrong computation changes the same teacher-forced continuation's logits.
    backend.model.scale.forward = lambda value: original(value) + 3.0
    report = resident.quality(ids, oracle)
    # Then: raw numerical errors reject the model; no scalar-score fake is involved.
    assert not report.valid
    raw = json.loads(report.raw_path.read_text())["data"]
    assert len(raw["prompts"]) == 2
    assert all(p["valid_tokens"] == 32 for p in raw["prompts"])
    assert report.metrics["logits_relative_l2_max"] > 0.01


def test_short_decode_when_completion_record_is_incomplete(tmp_path: Path) -> None:
    # Given: a real generated single-request record, then a missing output token.
    from examples.c3_qwen3.runner_measure import score_waves
    from examples.c3_qwen3.runner_records import RunnerError, WaveRecord
    resident, _, prepared = runner(tmp_path)
    goal = next(g for g in prepared.contract.goals if g.id == "single")
    report = resident.measure(goal, goal.search_prompt_ids)
    waves = tuple(WaveRecord.model_validate(w) for w in json.loads(report.raw_path.read_text())["data"]["waves"])
    shortened = waves[-1].model_copy(update={"tokens": (waves[-1].tokens[0][:-1],)})
    # When / Then: incomplete execution cannot yield a native throughput score.
    with pytest.raises(RunnerError, match="incomplete"):
        score_waves(goal, (*waves[:-1], shortened))


def test_shared_kv_when_backend_retains_previous_request_state(tmp_path: Path) -> None:
    # Given: a backend defect that advances position ahead of the real input prefix.
    resident, backend, prepared = runner(tmp_path)
    goal = next(g for g in prepared.contract.goals if g.id == "ttft")
    backend.cache_length = lambda: 4097
    # When: a real forward runs but its state is inconsistent.
    report = resident.measure(goal, goal.search_prompt_ids)
    # Then: position failure has no valid timing score.
    assert not report.evaluation.valid
    assert report.evaluation.score is None
    assert "KV" in report.evaluation.detail
    waves = json.loads(report.raw_path.read_text())["data"]["waves"]
    assert waves and not waves[0]["complete"]
    assert len(waves[0]["token_ready_s"]) == 1


def test_load_once_when_injected_backend_handles_multiple_trials(tmp_path: Path) -> None:
    # Given: a factory representing the model load boundary, not a cached metric.
    api = importlib.import_module("examples.c3_qwen3.model_runner")
    prepared = api.prepare(RAW / "contract.json", RAW / "preflight.json")
    constructed: list[TinyBackend] = []
    def factory(asset, device):
        backend = TinyBackend()
        constructed.append(backend)
        return backend
    resident = api.load(prepared.asset_spec, "cpu", backend_factory=factory)
    resident.output_dir = tmp_path
    goal = prepared.contract.goals[0]
    # When: two measurements use one loaded model and separate state.
    resident.measure(goal, goal.search_prompt_ids)
    resident.measure(goal, goal.search_prompt_ids)
    resident.close()
    # Then: construction occurs once and owned model references are released.
    assert len(constructed) == 1
    assert not resident.binding.modules


def test_cli_help_when_gpu_libraries_are_absent() -> None:
    # Given: the real Python module CLI, in the existing CPU-only environment.
    # When: help is requested, without model load or installation.
    result = subprocess.run([sys.executable, "-B", "-m", "examples.c3_qwen3.model_runner", "--help"],
                            cwd=ROOT, capture_output=True, text=True, check=False)
    # Then: actual public CLI parsing works and exposes CPU preparation.
    assert result.returncode == 0, result.stderr
    assert "prepare" in result.stdout


def test_bound_candidate_when_quality_then_measure_uses_rewrite(tmp_path: Path) -> None:
    # Given: a real original oracle and actual call fixtures on a named numerical module.
    from tests.test_c3_model_binding import make_bundle
    resident, _, prepared = runner(tmp_path)
    ids = ("calibration-calibration-00", "calibration-calibration-01")
    resident.binding.register_site("scale", ("scale",))
    oracle = resident.create_oracles(ids)
    resident.capture_fixtures(ids)
    bundle = make_bundle(tmp_path / "candidate", "def replace(site, call, params):\n    return call.args[0] * factor\n")
    resident.bind(bundle)
    # When: quality and timed workload use the same complete installed bundle.
    quality = resident.quality(ids, oracle)
    goal = prepared.contract.goals[0]
    result = resident.measure(goal, goal.search_prompt_ids)
    # Then: the runner owns the measured score and execution identity.
    assert quality.valid, quality.detail
    assert result.evaluation.valid, result.evaluation.detail
    raw = json.loads(result.raw_path.read_text())
    assert raw["binding"]["bundle_sha256"] == bundle.bundle_sha256


def test_baseline_profile_when_trace_is_requested(tmp_path: Path) -> None:
    # Given: an unbound original numerical model and the real TTFT shape.
    resident, _, prepared = runner(tmp_path)
    assert hasattr(resident, "profile"), "baseline diagnostic phase trace is absent"
    goal = prepared.contract.goals[0]
    # When: a separate diagnostic invocation traces real named-module calls.
    path = resident.profile(goal, goal.search_prompt_ids)
    # Then: source, phase and shape came from executed calls, not a preset goal/site map.
    data = json.loads(path.read_text())["data"]
    assert any(row["module_path"] == "scale" and row["phase"] == "prefill" for row in data["trace"])
    assert not resident.binding.sites
    resident.binding.register_site("selected-group", ("scale",))


def test_quality_when_oracle_tensor_bytes_are_changed(tmp_path: Path) -> None:
    # Given: a baseline continuation manifest with authenticated logits.
    resident, _, _ = runner(tmp_path)
    ids = ("calibration-calibration-00", "calibration-calibration-01")
    oracle = resident.create_oracles(ids)
    document = json.loads(oracle.read_text())
    tensor = oracle.parent / document["prompts"][0]["logits_file"]
    # When: logits no longer match the recorded original-baseline identity.
    tensor.write_bytes(b"changed")
    report = resident.quality(ids, oracle)
    # Then: no quality score survives the stale oracle.
    assert not report.valid
    assert "hash mismatch" in report.detail


def test_wrong_operator_when_only_target_shape_falls_back(tmp_path: Path) -> None:
    # Given: short calibration uses the rewrite, while the formal long prompt calls old code.
    from tests.test_c3_model_binding import make_bundle
    resident, _, prepared = runner(tmp_path)
    ids = ("calibration-calibration-00", "calibration-calibration-01")
    threshold = max(sum(prepared.prompts_by_id[p].input_ids) for p in ids) + 32 * 7
    resident.binding.register_site("scale", ("scale",))
    oracle = resident.create_oracles(ids)
    resident.capture_fixtures(ids)
    body = ("def replace(site, call, params):\n"
            f"    if call.args[0] > {threshold}:\n        return site.module.original(*call.args)\n"
            "    return call.args[0] * factor\n")
    resident.bind(make_bundle(tmp_path / "candidate", body))
    assert resident.quality(ids, oracle).valid
    goal = prepared.contract.goals[0]
    # When: the single required same-shape warmup checks actual target dispatch.
    report = resident.measure(goal, goal.search_prompt_ids)
    # Then: no formal score is emitted for a shape-dependent fallback wrapper.
    assert not report.evaluation.valid
    assert "exclusively" in report.evaluation.detail


def test_stale_function_when_dispatch_changes_after_quality(tmp_path: Path) -> None:
    # Given: validated candidate dispatch and an obsolete original-forward pointer.
    from tests.test_c3_model_binding import make_bundle
    resident, backend, _ = runner(tmp_path)
    ids = ("calibration-calibration-00", "calibration-calibration-01")
    original = backend.model.scale.forward
    resident.binding.register_site("scale", ("scale",))
    oracle = resident.create_oracles(ids)
    resident.capture_fixtures(ids)
    resident.bind(make_bundle(tmp_path / "candidate", "def replace(site, call, params):\n    return call.args[0] * factor\n"))
    assert resident.quality(ids, oracle).valid
    # When: another caller silently replaces the installed dispatch.
    backend.model.scale.forward = original
    # Then: the runner rejects stale identity rather than silently repairing it before timing.
    assert hasattr(resident.binding, "verify_installed"), "dispatch identity validation is absent"
    with pytest.raises(RuntimeError, match="dispatch"):
        resident.binding.verify_installed()


def test_failed_measurement_when_weights_mutate_closes_runner(tmp_path: Path) -> None:
    # Given: a failing forward that also corrupts resident immutable weights.
    resident, backend, prepared = runner(tmp_path)
    def corrupt(value: float) -> float:
        backend.model.scale.weight = 3.0
        raise ArithmeticError("corrupted then failed")
    backend.model.scale.forward = corrupt
    goal = prepared.contract.goals[0]
    # When: failure occurs before normal post-measurement validation.
    report = resident.measure(goal, goal.search_prompt_ids)
    # Then: invalid data is retained and the poisoned model cannot be reused.
    assert not report.evaluation.valid
    assert resident.closed
